#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReCaptchaApp.Droid.Resource", IsApplication=true)]

namespace ReCaptchaApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::ReCaptchaApp.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int abc_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int abc_fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int abc_grow_fade_in_from_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int abc_popup_enter = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int abc_popup_exit = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int abc_shrink_fade_out_from_bottom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int abc_slide_in_bottom = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int abc_slide_in_top = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int abc_slide_out_bottom = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int abc_slide_out_top = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int design_bottom_sheet_slide_in = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int design_bottom_sheet_slide_out = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int design_fab_in = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int design_fab_out = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int design_snackbar_in = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int design_snackbar_out = 2130968591;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int design_appbar_state_list_animator = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01005f
			public const int actionBarDivider = 2130772063;
			
			// aapt resource value: 0x7f010060
			public const int actionBarItemBackground = 2130772064;
			
			// aapt resource value: 0x7f010059
			public const int actionBarPopupTheme = 2130772057;
			
			// aapt resource value: 0x7f01005e
			public const int actionBarSize = 2130772062;
			
			// aapt resource value: 0x7f01005b
			public const int actionBarSplitStyle = 2130772059;
			
			// aapt resource value: 0x7f01005a
			public const int actionBarStyle = 2130772058;
			
			// aapt resource value: 0x7f010055
			public const int actionBarTabBarStyle = 2130772053;
			
			// aapt resource value: 0x7f010054
			public const int actionBarTabStyle = 2130772052;
			
			// aapt resource value: 0x7f010056
			public const int actionBarTabTextStyle = 2130772054;
			
			// aapt resource value: 0x7f01005c
			public const int actionBarTheme = 2130772060;
			
			// aapt resource value: 0x7f01005d
			public const int actionBarWidgetTheme = 2130772061;
			
			// aapt resource value: 0x7f01007a
			public const int actionButtonStyle = 2130772090;
			
			// aapt resource value: 0x7f010076
			public const int actionDropDownStyle = 2130772086;
			
			// aapt resource value: 0x7f0100cc
			public const int actionLayout = 2130772172;
			
			// aapt resource value: 0x7f010061
			public const int actionMenuTextAppearance = 2130772065;
			
			// aapt resource value: 0x7f010062
			public const int actionMenuTextColor = 2130772066;
			
			// aapt resource value: 0x7f010065
			public const int actionModeBackground = 2130772069;
			
			// aapt resource value: 0x7f010064
			public const int actionModeCloseButtonStyle = 2130772068;
			
			// aapt resource value: 0x7f010067
			public const int actionModeCloseDrawable = 2130772071;
			
			// aapt resource value: 0x7f010069
			public const int actionModeCopyDrawable = 2130772073;
			
			// aapt resource value: 0x7f010068
			public const int actionModeCutDrawable = 2130772072;
			
			// aapt resource value: 0x7f01006d
			public const int actionModeFindDrawable = 2130772077;
			
			// aapt resource value: 0x7f01006a
			public const int actionModePasteDrawable = 2130772074;
			
			// aapt resource value: 0x7f01006f
			public const int actionModePopupWindowStyle = 2130772079;
			
			// aapt resource value: 0x7f01006b
			public const int actionModeSelectAllDrawable = 2130772075;
			
			// aapt resource value: 0x7f01006c
			public const int actionModeShareDrawable = 2130772076;
			
			// aapt resource value: 0x7f010066
			public const int actionModeSplitBackground = 2130772070;
			
			// aapt resource value: 0x7f010063
			public const int actionModeStyle = 2130772067;
			
			// aapt resource value: 0x7f01006e
			public const int actionModeWebSearchDrawable = 2130772078;
			
			// aapt resource value: 0x7f010057
			public const int actionOverflowButtonStyle = 2130772055;
			
			// aapt resource value: 0x7f010058
			public const int actionOverflowMenuStyle = 2130772056;
			
			// aapt resource value: 0x7f0100ce
			public const int actionProviderClass = 2130772174;
			
			// aapt resource value: 0x7f0100cd
			public const int actionViewClass = 2130772173;
			
			// aapt resource value: 0x7f010082
			public const int activityChooserViewStyle = 2130772098;
			
			// aapt resource value: 0x7f0100a7
			public const int alertDialogButtonGroupStyle = 2130772135;
			
			// aapt resource value: 0x7f0100a8
			public const int alertDialogCenterButtons = 2130772136;
			
			// aapt resource value: 0x7f0100a6
			public const int alertDialogStyle = 2130772134;
			
			// aapt resource value: 0x7f0100a9
			public const int alertDialogTheme = 2130772137;
			
			// aapt resource value: 0x7f0100bc
			public const int allowStacking = 2130772156;
			
			// aapt resource value: 0x7f0100bd
			public const int alpha = 2130772157;
			
			// aapt resource value: 0x7f0100c4
			public const int arrowHeadLength = 2130772164;
			
			// aapt resource value: 0x7f0100c5
			public const int arrowShaftLength = 2130772165;
			
			// aapt resource value: 0x7f0100ae
			public const int autoCompleteTextViewStyle = 2130772142;
			
			// aapt resource value: 0x7f010028
			public const int background = 2130772008;
			
			// aapt resource value: 0x7f01002a
			public const int backgroundSplit = 2130772010;
			
			// aapt resource value: 0x7f010029
			public const int backgroundStacked = 2130772009;
			
			// aapt resource value: 0x7f010101
			public const int backgroundTint = 2130772225;
			
			// aapt resource value: 0x7f010102
			public const int backgroundTintMode = 2130772226;
			
			// aapt resource value: 0x7f0100c6
			public const int barLength = 2130772166;
			
			// aapt resource value: 0x7f01012c
			public const int behavior_autoHide = 2130772268;
			
			// aapt resource value: 0x7f010109
			public const int behavior_hideable = 2130772233;
			
			// aapt resource value: 0x7f010135
			public const int behavior_overlapTop = 2130772277;
			
			// aapt resource value: 0x7f010108
			public const int behavior_peekHeight = 2130772232;
			
			// aapt resource value: 0x7f01010a
			public const int behavior_skipCollapsed = 2130772234;
			
			// aapt resource value: 0x7f01012a
			public const int borderWidth = 2130772266;
			
			// aapt resource value: 0x7f01007f
			public const int borderlessButtonStyle = 2130772095;
			
			// aapt resource value: 0x7f010124
			public const int bottomSheetDialogTheme = 2130772260;
			
			// aapt resource value: 0x7f010125
			public const int bottomSheetStyle = 2130772261;
			
			// aapt resource value: 0x7f01007c
			public const int buttonBarButtonStyle = 2130772092;
			
			// aapt resource value: 0x7f0100ac
			public const int buttonBarNegativeButtonStyle = 2130772140;
			
			// aapt resource value: 0x7f0100ad
			public const int buttonBarNeutralButtonStyle = 2130772141;
			
			// aapt resource value: 0x7f0100ab
			public const int buttonBarPositiveButtonStyle = 2130772139;
			
			// aapt resource value: 0x7f01007b
			public const int buttonBarStyle = 2130772091;
			
			// aapt resource value: 0x7f0100f6
			public const int buttonGravity = 2130772214;
			
			// aapt resource value: 0x7f01003d
			public const int buttonPanelSideLayout = 2130772029;
			
			// aapt resource value: 0x7f0100af
			public const int buttonStyle = 2130772143;
			
			// aapt resource value: 0x7f0100b0
			public const int buttonStyleSmall = 2130772144;
			
			// aapt resource value: 0x7f0100be
			public const int buttonTint = 2130772158;
			
			// aapt resource value: 0x7f0100bf
			public const int buttonTintMode = 2130772159;
			
			// aapt resource value: 0x7f010011
			public const int cardBackgroundColor = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int cardCornerRadius = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int cardElevation = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int cardMaxElevation = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int cardPreventCornerOverlap = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int cardUseCompatPadding = 2130771989;
			
			// aapt resource value: 0x7f0100b1
			public const int checkboxStyle = 2130772145;
			
			// aapt resource value: 0x7f0100b2
			public const int checkedTextViewStyle = 2130772146;
			
			// aapt resource value: 0x7f0100d9
			public const int closeIcon = 2130772185;
			
			// aapt resource value: 0x7f01003a
			public const int closeItemLayout = 2130772026;
			
			// aapt resource value: 0x7f0100f8
			public const int collapseContentDescription = 2130772216;
			
			// aapt resource value: 0x7f0100f7
			public const int collapseIcon = 2130772215;
			
			// aapt resource value: 0x7f010117
			public const int collapsedTitleGravity = 2130772247;
			
			// aapt resource value: 0x7f010111
			public const int collapsedTitleTextAppearance = 2130772241;
			
			// aapt resource value: 0x7f0100c0
			public const int color = 2130772160;
			
			// aapt resource value: 0x7f01009e
			public const int colorAccent = 2130772126;
			
			// aapt resource value: 0x7f0100a5
			public const int colorBackgroundFloating = 2130772133;
			
			// aapt resource value: 0x7f0100a2
			public const int colorButtonNormal = 2130772130;
			
			// aapt resource value: 0x7f0100a0
			public const int colorControlActivated = 2130772128;
			
			// aapt resource value: 0x7f0100a1
			public const int colorControlHighlight = 2130772129;
			
			// aapt resource value: 0x7f01009f
			public const int colorControlNormal = 2130772127;
			
			// aapt resource value: 0x7f01009c
			public const int colorPrimary = 2130772124;
			
			// aapt resource value: 0x7f01009d
			public const int colorPrimaryDark = 2130772125;
			
			// aapt resource value: 0x7f0100a3
			public const int colorSwitchThumbNormal = 2130772131;
			
			// aapt resource value: 0x7f0100de
			public const int commitIcon = 2130772190;
			
			// aapt resource value: 0x7f010033
			public const int contentInsetEnd = 2130772019;
			
			// aapt resource value: 0x7f010037
			public const int contentInsetEndWithActions = 2130772023;
			
			// aapt resource value: 0x7f010034
			public const int contentInsetLeft = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int contentInsetRight = 2130772021;
			
			// aapt resource value: 0x7f010032
			public const int contentInsetStart = 2130772018;
			
			// aapt resource value: 0x7f010036
			public const int contentInsetStartWithNavigation = 2130772022;
			
			// aapt resource value: 0x7f010017
			public const int contentPadding = 2130771991;
			
			// aapt resource value: 0x7f01001b
			public const int contentPaddingBottom = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int contentPaddingLeft = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int contentPaddingRight = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int contentPaddingTop = 2130771994;
			
			// aapt resource value: 0x7f010112
			public const int contentScrim = 2130772242;
			
			// aapt resource value: 0x7f0100a4
			public const int controlBackground = 2130772132;
			
			// aapt resource value: 0x7f01014b
			public const int counterEnabled = 2130772299;
			
			// aapt resource value: 0x7f01014c
			public const int counterMaxLength = 2130772300;
			
			// aapt resource value: 0x7f01014e
			public const int counterOverflowTextAppearance = 2130772302;
			
			// aapt resource value: 0x7f01014d
			public const int counterTextAppearance = 2130772301;
			
			// aapt resource value: 0x7f01002b
			public const int customNavigationLayout = 2130772011;
			
			// aapt resource value: 0x7f0100d8
			public const int defaultQueryHint = 2130772184;
			
			// aapt resource value: 0x7f010074
			public const int dialogPreferredPadding = 2130772084;
			
			// aapt resource value: 0x7f010073
			public const int dialogTheme = 2130772083;
			
			// aapt resource value: 0x7f010021
			public const int displayOptions = 2130772001;
			
			// aapt resource value: 0x7f010027
			public const int divider = 2130772007;
			
			// aapt resource value: 0x7f010081
			public const int dividerHorizontal = 2130772097;
			
			// aapt resource value: 0x7f0100ca
			public const int dividerPadding = 2130772170;
			
			// aapt resource value: 0x7f010080
			public const int dividerVertical = 2130772096;
			
			// aapt resource value: 0x7f0100c2
			public const int drawableSize = 2130772162;
			
			// aapt resource value: 0x7f01001c
			public const int drawerArrowStyle = 2130771996;
			
			// aapt resource value: 0x7f010093
			public const int dropDownListViewStyle = 2130772115;
			
			// aapt resource value: 0x7f010077
			public const int dropdownListPreferredItemHeight = 2130772087;
			
			// aapt resource value: 0x7f010088
			public const int editTextBackground = 2130772104;
			
			// aapt resource value: 0x7f010087
			public const int editTextColor = 2130772103;
			
			// aapt resource value: 0x7f0100b3
			public const int editTextStyle = 2130772147;
			
			// aapt resource value: 0x7f010038
			public const int elevation = 2130772024;
			
			// aapt resource value: 0x7f010149
			public const int errorEnabled = 2130772297;
			
			// aapt resource value: 0x7f01014a
			public const int errorTextAppearance = 2130772298;
			
			// aapt resource value: 0x7f01003c
			public const int expandActivityOverflowButtonDrawable = 2130772028;
			
			// aapt resource value: 0x7f010103
			public const int expanded = 2130772227;
			
			// aapt resource value: 0x7f010118
			public const int expandedTitleGravity = 2130772248;
			
			// aapt resource value: 0x7f01010b
			public const int expandedTitleMargin = 2130772235;
			
			// aapt resource value: 0x7f01010f
			public const int expandedTitleMarginBottom = 2130772239;
			
			// aapt resource value: 0x7f01010e
			public const int expandedTitleMarginEnd = 2130772238;
			
			// aapt resource value: 0x7f01010c
			public const int expandedTitleMarginStart = 2130772236;
			
			// aapt resource value: 0x7f01010d
			public const int expandedTitleMarginTop = 2130772237;
			
			// aapt resource value: 0x7f010110
			public const int expandedTitleTextAppearance = 2130772240;
			
			// aapt resource value: 0x7f010010
			public const int externalRouteEnabledDrawable = 2130771984;
			
			// aapt resource value: 0x7f010128
			public const int fabSize = 2130772264;
			
			// aapt resource value: 0x7f01012d
			public const int foregroundInsidePadding = 2130772269;
			
			// aapt resource value: 0x7f0100c3
			public const int gapBetweenBars = 2130772163;
			
			// aapt resource value: 0x7f0100da
			public const int goIcon = 2130772186;
			
			// aapt resource value: 0x7f010133
			public const int headerLayout = 2130772275;
			
			// aapt resource value: 0x7f01001d
			public const int height = 2130771997;
			
			// aapt resource value: 0x7f010031
			public const int hideOnContentScroll = 2130772017;
			
			// aapt resource value: 0x7f01014f
			public const int hintAnimationEnabled = 2130772303;
			
			// aapt resource value: 0x7f010148
			public const int hintEnabled = 2130772296;
			
			// aapt resource value: 0x7f010147
			public const int hintTextAppearance = 2130772295;
			
			// aapt resource value: 0x7f010079
			public const int homeAsUpIndicator = 2130772089;
			
			// aapt resource value: 0x7f01002c
			public const int homeLayout = 2130772012;
			
			// aapt resource value: 0x7f010025
			public const int icon = 2130772005;
			
			// aapt resource value: 0x7f0100d6
			public const int iconifiedByDefault = 2130772182;
			
			// aapt resource value: 0x7f010089
			public const int imageButtonStyle = 2130772105;
			
			// aapt resource value: 0x7f01002e
			public const int indeterminateProgressStyle = 2130772014;
			
			// aapt resource value: 0x7f01003b
			public const int initialActivityCount = 2130772027;
			
			// aapt resource value: 0x7f010134
			public const int insetForeground = 2130772276;
			
			// aapt resource value: 0x7f01001e
			public const int isLightTheme = 2130771998;
			
			// aapt resource value: 0x7f010131
			public const int itemBackground = 2130772273;
			
			// aapt resource value: 0x7f01012f
			public const int itemIconTint = 2130772271;
			
			// aapt resource value: 0x7f010030
			public const int itemPadding = 2130772016;
			
			// aapt resource value: 0x7f010132
			public const int itemTextAppearance = 2130772274;
			
			// aapt resource value: 0x7f010130
			public const int itemTextColor = 2130772272;
			
			// aapt resource value: 0x7f01011c
			public const int keylines = 2130772252;
			
			// aapt resource value: 0x7f0100d5
			public const int layout = 2130772181;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f01011f
			public const int layout_anchor = 2130772255;
			
			// aapt resource value: 0x7f010121
			public const int layout_anchorGravity = 2130772257;
			
			// aapt resource value: 0x7f01011e
			public const int layout_behavior = 2130772254;
			
			// aapt resource value: 0x7f01011a
			public const int layout_collapseMode = 2130772250;
			
			// aapt resource value: 0x7f01011b
			public const int layout_collapseParallaxMultiplier = 2130772251;
			
			// aapt resource value: 0x7f010123
			public const int layout_dodgeInsetEdges = 2130772259;
			
			// aapt resource value: 0x7f010122
			public const int layout_insetEdge = 2130772258;
			
			// aapt resource value: 0x7f010120
			public const int layout_keyline = 2130772256;
			
			// aapt resource value: 0x7f010106
			public const int layout_scrollFlags = 2130772230;
			
			// aapt resource value: 0x7f010107
			public const int layout_scrollInterpolator = 2130772231;
			
			// aapt resource value: 0x7f01009b
			public const int listChoiceBackgroundIndicator = 2130772123;
			
			// aapt resource value: 0x7f010075
			public const int listDividerAlertDialog = 2130772085;
			
			// aapt resource value: 0x7f010041
			public const int listItemLayout = 2130772033;
			
			// aapt resource value: 0x7f01003e
			public const int listLayout = 2130772030;
			
			// aapt resource value: 0x7f0100bb
			public const int listMenuViewStyle = 2130772155;
			
			// aapt resource value: 0x7f010094
			public const int listPopupWindowStyle = 2130772116;
			
			// aapt resource value: 0x7f01008e
			public const int listPreferredItemHeight = 2130772110;
			
			// aapt resource value: 0x7f010090
			public const int listPreferredItemHeightLarge = 2130772112;
			
			// aapt resource value: 0x7f01008f
			public const int listPreferredItemHeightSmall = 2130772111;
			
			// aapt resource value: 0x7f010091
			public const int listPreferredItemPaddingLeft = 2130772113;
			
			// aapt resource value: 0x7f010092
			public const int listPreferredItemPaddingRight = 2130772114;
			
			// aapt resource value: 0x7f010026
			public const int logo = 2130772006;
			
			// aapt resource value: 0x7f0100fb
			public const int logoDescription = 2130772219;
			
			// aapt resource value: 0x7f010136
			public const int maxActionInlineWidth = 2130772278;
			
			// aapt resource value: 0x7f0100f5
			public const int maxButtonHeight = 2130772213;
			
			// aapt resource value: 0x7f0100c8
			public const int measureWithLargestChild = 2130772168;
			
			// aapt resource value: 0x7f010004
			public const int mediaRouteAudioTrackDrawable = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int mediaRouteButtonStyle = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int mediaRouteCloseDrawable = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int mediaRouteControlPanelThemeOverlay = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int mediaRouteDefaultIconDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int mediaRoutePauseDrawable = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int mediaRoutePlayDrawable = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int mediaRouteSpeakerGroupIconDrawable = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int mediaRouteSpeakerIconDrawable = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int mediaRouteStopDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int mediaRouteTheme = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int mediaRouteTvIconDrawable = 2130771983;
			
			// aapt resource value: 0x7f01012e
			public const int menu = 2130772270;
			
			// aapt resource value: 0x7f01003f
			public const int multiChoiceItemLayout = 2130772031;
			
			// aapt resource value: 0x7f0100fa
			public const int navigationContentDescription = 2130772218;
			
			// aapt resource value: 0x7f0100f9
			public const int navigationIcon = 2130772217;
			
			// aapt resource value: 0x7f010020
			public const int navigationMode = 2130772000;
			
			// aapt resource value: 0x7f0100d1
			public const int overlapAnchor = 2130772177;
			
			// aapt resource value: 0x7f0100d3
			public const int paddingBottomNoButtons = 2130772179;
			
			// aapt resource value: 0x7f0100ff
			public const int paddingEnd = 2130772223;
			
			// aapt resource value: 0x7f0100fe
			public const int paddingStart = 2130772222;
			
			// aapt resource value: 0x7f0100d4
			public const int paddingTopNoTitle = 2130772180;
			
			// aapt resource value: 0x7f010098
			public const int panelBackground = 2130772120;
			
			// aapt resource value: 0x7f01009a
			public const int panelMenuListTheme = 2130772122;
			
			// aapt resource value: 0x7f010099
			public const int panelMenuListWidth = 2130772121;
			
			// aapt resource value: 0x7f010152
			public const int passwordToggleContentDescription = 2130772306;
			
			// aapt resource value: 0x7f010151
			public const int passwordToggleDrawable = 2130772305;
			
			// aapt resource value: 0x7f010150
			public const int passwordToggleEnabled = 2130772304;
			
			// aapt resource value: 0x7f010153
			public const int passwordToggleTint = 2130772307;
			
			// aapt resource value: 0x7f010154
			public const int passwordToggleTintMode = 2130772308;
			
			// aapt resource value: 0x7f010085
			public const int popupMenuStyle = 2130772101;
			
			// aapt resource value: 0x7f010039
			public const int popupTheme = 2130772025;
			
			// aapt resource value: 0x7f010086
			public const int popupWindowStyle = 2130772102;
			
			// aapt resource value: 0x7f0100cf
			public const int preserveIconSpacing = 2130772175;
			
			// aapt resource value: 0x7f010129
			public const int pressedTranslationZ = 2130772265;
			
			// aapt resource value: 0x7f01002f
			public const int progressBarPadding = 2130772015;
			
			// aapt resource value: 0x7f01002d
			public const int progressBarStyle = 2130772013;
			
			// aapt resource value: 0x7f0100e0
			public const int queryBackground = 2130772192;
			
			// aapt resource value: 0x7f0100d7
			public const int queryHint = 2130772183;
			
			// aapt resource value: 0x7f0100b4
			public const int radioButtonStyle = 2130772148;
			
			// aapt resource value: 0x7f0100b5
			public const int ratingBarStyle = 2130772149;
			
			// aapt resource value: 0x7f0100b6
			public const int ratingBarStyleIndicator = 2130772150;
			
			// aapt resource value: 0x7f0100b7
			public const int ratingBarStyleSmall = 2130772151;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010127
			public const int rippleColor = 2130772263;
			
			// aapt resource value: 0x7f010116
			public const int scrimAnimationDuration = 2130772246;
			
			// aapt resource value: 0x7f010115
			public const int scrimVisibleHeightTrigger = 2130772245;
			
			// aapt resource value: 0x7f0100dc
			public const int searchHintIcon = 2130772188;
			
			// aapt resource value: 0x7f0100db
			public const int searchIcon = 2130772187;
			
			// aapt resource value: 0x7f01008d
			public const int searchViewStyle = 2130772109;
			
			// aapt resource value: 0x7f0100b8
			public const int seekBarStyle = 2130772152;
			
			// aapt resource value: 0x7f01007d
			public const int selectableItemBackground = 2130772093;
			
			// aapt resource value: 0x7f01007e
			public const int selectableItemBackgroundBorderless = 2130772094;
			
			// aapt resource value: 0x7f0100cb
			public const int showAsAction = 2130772171;
			
			// aapt resource value: 0x7f0100c9
			public const int showDividers = 2130772169;
			
			// aapt resource value: 0x7f0100ec
			public const int showText = 2130772204;
			
			// aapt resource value: 0x7f010042
			public const int showTitle = 2130772034;
			
			// aapt resource value: 0x7f010040
			public const int singleChoiceItemLayout = 2130772032;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f0100c1
			public const int spinBars = 2130772161;
			
			// aapt resource value: 0x7f010078
			public const int spinnerDropDownItemStyle = 2130772088;
			
			// aapt resource value: 0x7f0100b9
			public const int spinnerStyle = 2130772153;
			
			// aapt resource value: 0x7f0100eb
			public const int splitTrack = 2130772203;
			
			// aapt resource value: 0x7f010043
			public const int srcCompat = 2130772035;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f0100d2
			public const int state_above_anchor = 2130772178;
			
			// aapt resource value: 0x7f010104
			public const int state_collapsed = 2130772228;
			
			// aapt resource value: 0x7f010105
			public const int state_collapsible = 2130772229;
			
			// aapt resource value: 0x7f01011d
			public const int statusBarBackground = 2130772253;
			
			// aapt resource value: 0x7f010113
			public const int statusBarScrim = 2130772243;
			
			// aapt resource value: 0x7f0100d0
			public const int subMenuArrow = 2130772176;
			
			// aapt resource value: 0x7f0100e1
			public const int submitBackground = 2130772193;
			
			// aapt resource value: 0x7f010022
			public const int subtitle = 2130772002;
			
			// aapt resource value: 0x7f0100ee
			public const int subtitleTextAppearance = 2130772206;
			
			// aapt resource value: 0x7f0100fd
			public const int subtitleTextColor = 2130772221;
			
			// aapt resource value: 0x7f010024
			public const int subtitleTextStyle = 2130772004;
			
			// aapt resource value: 0x7f0100df
			public const int suggestionRowLayout = 2130772191;
			
			// aapt resource value: 0x7f0100e9
			public const int switchMinWidth = 2130772201;
			
			// aapt resource value: 0x7f0100ea
			public const int switchPadding = 2130772202;
			
			// aapt resource value: 0x7f0100ba
			public const int switchStyle = 2130772154;
			
			// aapt resource value: 0x7f0100e8
			public const int switchTextAppearance = 2130772200;
			
			// aapt resource value: 0x7f01013a
			public const int tabBackground = 2130772282;
			
			// aapt resource value: 0x7f010139
			public const int tabContentStart = 2130772281;
			
			// aapt resource value: 0x7f01013c
			public const int tabGravity = 2130772284;
			
			// aapt resource value: 0x7f010137
			public const int tabIndicatorColor = 2130772279;
			
			// aapt resource value: 0x7f010138
			public const int tabIndicatorHeight = 2130772280;
			
			// aapt resource value: 0x7f01013e
			public const int tabMaxWidth = 2130772286;
			
			// aapt resource value: 0x7f01013d
			public const int tabMinWidth = 2130772285;
			
			// aapt resource value: 0x7f01013b
			public const int tabMode = 2130772283;
			
			// aapt resource value: 0x7f010146
			public const int tabPadding = 2130772294;
			
			// aapt resource value: 0x7f010145
			public const int tabPaddingBottom = 2130772293;
			
			// aapt resource value: 0x7f010144
			public const int tabPaddingEnd = 2130772292;
			
			// aapt resource value: 0x7f010142
			public const int tabPaddingStart = 2130772290;
			
			// aapt resource value: 0x7f010143
			public const int tabPaddingTop = 2130772291;
			
			// aapt resource value: 0x7f010141
			public const int tabSelectedTextColor = 2130772289;
			
			// aapt resource value: 0x7f01013f
			public const int tabTextAppearance = 2130772287;
			
			// aapt resource value: 0x7f010140
			public const int tabTextColor = 2130772288;
			
			// aapt resource value: 0x7f010049
			public const int textAllCaps = 2130772041;
			
			// aapt resource value: 0x7f010070
			public const int textAppearanceLargePopupMenu = 2130772080;
			
			// aapt resource value: 0x7f010095
			public const int textAppearanceListItem = 2130772117;
			
			// aapt resource value: 0x7f010096
			public const int textAppearanceListItemSecondary = 2130772118;
			
			// aapt resource value: 0x7f010097
			public const int textAppearanceListItemSmall = 2130772119;
			
			// aapt resource value: 0x7f010072
			public const int textAppearancePopupMenuHeader = 2130772082;
			
			// aapt resource value: 0x7f01008b
			public const int textAppearanceSearchResultSubtitle = 2130772107;
			
			// aapt resource value: 0x7f01008a
			public const int textAppearanceSearchResultTitle = 2130772106;
			
			// aapt resource value: 0x7f010071
			public const int textAppearanceSmallPopupMenu = 2130772081;
			
			// aapt resource value: 0x7f0100aa
			public const int textColorAlertDialogListItem = 2130772138;
			
			// aapt resource value: 0x7f010126
			public const int textColorError = 2130772262;
			
			// aapt resource value: 0x7f01008c
			public const int textColorSearchUrl = 2130772108;
			
			// aapt resource value: 0x7f010100
			public const int theme = 2130772224;
			
			// aapt resource value: 0x7f0100c7
			public const int thickness = 2130772167;
			
			// aapt resource value: 0x7f0100e7
			public const int thumbTextPadding = 2130772199;
			
			// aapt resource value: 0x7f0100e2
			public const int thumbTint = 2130772194;
			
			// aapt resource value: 0x7f0100e3
			public const int thumbTintMode = 2130772195;
			
			// aapt resource value: 0x7f010046
			public const int tickMark = 2130772038;
			
			// aapt resource value: 0x7f010047
			public const int tickMarkTint = 2130772039;
			
			// aapt resource value: 0x7f010048
			public const int tickMarkTintMode = 2130772040;
			
			// aapt resource value: 0x7f010044
			public const int tint = 2130772036;
			
			// aapt resource value: 0x7f010045
			public const int tintMode = 2130772037;
			
			// aapt resource value: 0x7f01001f
			public const int title = 2130771999;
			
			// aapt resource value: 0x7f010119
			public const int titleEnabled = 2130772249;
			
			// aapt resource value: 0x7f0100ef
			public const int titleMargin = 2130772207;
			
			// aapt resource value: 0x7f0100f3
			public const int titleMarginBottom = 2130772211;
			
			// aapt resource value: 0x7f0100f1
			public const int titleMarginEnd = 2130772209;
			
			// aapt resource value: 0x7f0100f0
			public const int titleMarginStart = 2130772208;
			
			// aapt resource value: 0x7f0100f2
			public const int titleMarginTop = 2130772210;
			
			// aapt resource value: 0x7f0100f4
			public const int titleMargins = 2130772212;
			
			// aapt resource value: 0x7f0100ed
			public const int titleTextAppearance = 2130772205;
			
			// aapt resource value: 0x7f0100fc
			public const int titleTextColor = 2130772220;
			
			// aapt resource value: 0x7f010023
			public const int titleTextStyle = 2130772003;
			
			// aapt resource value: 0x7f010114
			public const int toolbarId = 2130772244;
			
			// aapt resource value: 0x7f010084
			public const int toolbarNavigationButtonStyle = 2130772100;
			
			// aapt resource value: 0x7f010083
			public const int toolbarStyle = 2130772099;
			
			// aapt resource value: 0x7f0100e4
			public const int track = 2130772196;
			
			// aapt resource value: 0x7f0100e5
			public const int trackTint = 2130772197;
			
			// aapt resource value: 0x7f0100e6
			public const int trackTintMode = 2130772198;
			
			// aapt resource value: 0x7f01012b
			public const int useCompatPadding = 2130772267;
			
			// aapt resource value: 0x7f0100dd
			public const int voiceIcon = 2130772189;
			
			// aapt resource value: 0x7f01004a
			public const int windowActionBar = 2130772042;
			
			// aapt resource value: 0x7f01004c
			public const int windowActionBarOverlay = 2130772044;
			
			// aapt resource value: 0x7f01004d
			public const int windowActionModeOverlay = 2130772045;
			
			// aapt resource value: 0x7f010051
			public const int windowFixedHeightMajor = 2130772049;
			
			// aapt resource value: 0x7f01004f
			public const int windowFixedHeightMinor = 2130772047;
			
			// aapt resource value: 0x7f01004e
			public const int windowFixedWidthMajor = 2130772046;
			
			// aapt resource value: 0x7f010050
			public const int windowFixedWidthMinor = 2130772048;
			
			// aapt resource value: 0x7f010052
			public const int windowMinWidthMajor = 2130772050;
			
			// aapt resource value: 0x7f010053
			public const int windowMinWidthMinor = 2130772051;
			
			// aapt resource value: 0x7f01004b
			public const int windowNoTitle = 2130772043;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0d0000
			public const int abc_action_bar_embed_tabs = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int abc_allow_stacked_button_bar = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int abc_config_actionMenuItemAllCaps = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int abc_config_closeDialogWhenTouchOutside = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131558404;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0c004a
			public const int abc_background_cache_hint_selector_material_dark = 2131492938;
			
			// aapt resource value: 0x7f0c004b
			public const int abc_background_cache_hint_selector_material_light = 2131492939;
			
			// aapt resource value: 0x7f0c004c
			public const int abc_btn_colored_borderless_text_material = 2131492940;
			
			// aapt resource value: 0x7f0c004d
			public const int abc_btn_colored_text_material = 2131492941;
			
			// aapt resource value: 0x7f0c004e
			public const int abc_color_highlight_material = 2131492942;
			
			// aapt resource value: 0x7f0c004f
			public const int abc_hint_foreground_material_dark = 2131492943;
			
			// aapt resource value: 0x7f0c0050
			public const int abc_hint_foreground_material_light = 2131492944;
			
			// aapt resource value: 0x7f0c0005
			public const int abc_input_method_navigation_guard = 2131492869;
			
			// aapt resource value: 0x7f0c0051
			public const int abc_primary_text_disable_only_material_dark = 2131492945;
			
			// aapt resource value: 0x7f0c0052
			public const int abc_primary_text_disable_only_material_light = 2131492946;
			
			// aapt resource value: 0x7f0c0053
			public const int abc_primary_text_material_dark = 2131492947;
			
			// aapt resource value: 0x7f0c0054
			public const int abc_primary_text_material_light = 2131492948;
			
			// aapt resource value: 0x7f0c0055
			public const int abc_search_url_text = 2131492949;
			
			// aapt resource value: 0x7f0c0006
			public const int abc_search_url_text_normal = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public const int abc_search_url_text_pressed = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int abc_search_url_text_selected = 2131492872;
			
			// aapt resource value: 0x7f0c0056
			public const int abc_secondary_text_material_dark = 2131492950;
			
			// aapt resource value: 0x7f0c0057
			public const int abc_secondary_text_material_light = 2131492951;
			
			// aapt resource value: 0x7f0c0058
			public const int abc_tint_btn_checkable = 2131492952;
			
			// aapt resource value: 0x7f0c0059
			public const int abc_tint_default = 2131492953;
			
			// aapt resource value: 0x7f0c005a
			public const int abc_tint_edittext = 2131492954;
			
			// aapt resource value: 0x7f0c005b
			public const int abc_tint_seek_thumb = 2131492955;
			
			// aapt resource value: 0x7f0c005c
			public const int abc_tint_spinner = 2131492956;
			
			// aapt resource value: 0x7f0c005d
			public const int abc_tint_switch_thumb = 2131492957;
			
			// aapt resource value: 0x7f0c005e
			public const int abc_tint_switch_track = 2131492958;
			
			// aapt resource value: 0x7f0c0009
			public const int accent_material_dark = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int accent_material_light = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public const int background_floating_material_dark = 2131492875;
			
			// aapt resource value: 0x7f0c000c
			public const int background_floating_material_light = 2131492876;
			
			// aapt resource value: 0x7f0c000d
			public const int background_material_dark = 2131492877;
			
			// aapt resource value: 0x7f0c000e
			public const int background_material_light = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int bright_foreground_disabled_material_dark = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int bright_foreground_disabled_material_light = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int bright_foreground_inverse_material_dark = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int bright_foreground_inverse_material_light = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int bright_foreground_material_dark = 2131492883;
			
			// aapt resource value: 0x7f0c0014
			public const int bright_foreground_material_light = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int button_material_dark = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int button_material_light = 2131492886;
			
			// aapt resource value: 0x7f0c0000
			public const int cardview_dark_background = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int cardview_light_background = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int cardview_shadow_end_color = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int cardview_shadow_start_color = 2131492867;
			
			// aapt resource value: 0x7f0c003f
			public const int design_bottom_navigation_shadow_color = 2131492927;
			
			// aapt resource value: 0x7f0c005f
			public const int design_error = 2131492959;
			
			// aapt resource value: 0x7f0c0040
			public const int design_fab_shadow_end_color = 2131492928;
			
			// aapt resource value: 0x7f0c0041
			public const int design_fab_shadow_mid_color = 2131492929;
			
			// aapt resource value: 0x7f0c0042
			public const int design_fab_shadow_start_color = 2131492930;
			
			// aapt resource value: 0x7f0c0043
			public const int design_fab_stroke_end_inner_color = 2131492931;
			
			// aapt resource value: 0x7f0c0044
			public const int design_fab_stroke_end_outer_color = 2131492932;
			
			// aapt resource value: 0x7f0c0045
			public const int design_fab_stroke_top_inner_color = 2131492933;
			
			// aapt resource value: 0x7f0c0046
			public const int design_fab_stroke_top_outer_color = 2131492934;
			
			// aapt resource value: 0x7f0c0047
			public const int design_snackbar_background_color = 2131492935;
			
			// aapt resource value: 0x7f0c0048
			public const int design_textinput_error_color_dark = 2131492936;
			
			// aapt resource value: 0x7f0c0049
			public const int design_textinput_error_color_light = 2131492937;
			
			// aapt resource value: 0x7f0c0060
			public const int design_tint_password_toggle = 2131492960;
			
			// aapt resource value: 0x7f0c0017
			public const int dim_foreground_disabled_material_dark = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public const int dim_foreground_disabled_material_light = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public const int dim_foreground_material_dark = 2131492889;
			
			// aapt resource value: 0x7f0c001a
			public const int dim_foreground_material_light = 2131492890;
			
			// aapt resource value: 0x7f0c001b
			public const int foreground_material_dark = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public const int foreground_material_light = 2131492892;
			
			// aapt resource value: 0x7f0c001d
			public const int highlighted_text_material_dark = 2131492893;
			
			// aapt resource value: 0x7f0c001e
			public const int highlighted_text_material_light = 2131492894;
			
			// aapt resource value: 0x7f0c001f
			public const int material_blue_grey_800 = 2131492895;
			
			// aapt resource value: 0x7f0c0020
			public const int material_blue_grey_900 = 2131492896;
			
			// aapt resource value: 0x7f0c0021
			public const int material_blue_grey_950 = 2131492897;
			
			// aapt resource value: 0x7f0c0022
			public const int material_deep_teal_200 = 2131492898;
			
			// aapt resource value: 0x7f0c0023
			public const int material_deep_teal_500 = 2131492899;
			
			// aapt resource value: 0x7f0c0024
			public const int material_grey_100 = 2131492900;
			
			// aapt resource value: 0x7f0c0025
			public const int material_grey_300 = 2131492901;
			
			// aapt resource value: 0x7f0c0026
			public const int material_grey_50 = 2131492902;
			
			// aapt resource value: 0x7f0c0027
			public const int material_grey_600 = 2131492903;
			
			// aapt resource value: 0x7f0c0028
			public const int material_grey_800 = 2131492904;
			
			// aapt resource value: 0x7f0c0029
			public const int material_grey_850 = 2131492905;
			
			// aapt resource value: 0x7f0c002a
			public const int material_grey_900 = 2131492906;
			
			// aapt resource value: 0x7f0c0004
			public const int notification_action_color_filter = 2131492868;
			
			// aapt resource value: 0x7f0c002b
			public const int notification_icon_bg_color = 2131492907;
			
			// aapt resource value: 0x7f0c002c
			public const int notification_material_background_media_default_color = 2131492908;
			
			// aapt resource value: 0x7f0c002d
			public const int primary_dark_material_dark = 2131492909;
			
			// aapt resource value: 0x7f0c002e
			public const int primary_dark_material_light = 2131492910;
			
			// aapt resource value: 0x7f0c002f
			public const int primary_material_dark = 2131492911;
			
			// aapt resource value: 0x7f0c0030
			public const int primary_material_light = 2131492912;
			
			// aapt resource value: 0x7f0c0031
			public const int primary_text_default_material_dark = 2131492913;
			
			// aapt resource value: 0x7f0c0032
			public const int primary_text_default_material_light = 2131492914;
			
			// aapt resource value: 0x7f0c0033
			public const int primary_text_disabled_material_dark = 2131492915;
			
			// aapt resource value: 0x7f0c0034
			public const int primary_text_disabled_material_light = 2131492916;
			
			// aapt resource value: 0x7f0c0035
			public const int ripple_material_dark = 2131492917;
			
			// aapt resource value: 0x7f0c0036
			public const int ripple_material_light = 2131492918;
			
			// aapt resource value: 0x7f0c0037
			public const int secondary_text_default_material_dark = 2131492919;
			
			// aapt resource value: 0x7f0c0038
			public const int secondary_text_default_material_light = 2131492920;
			
			// aapt resource value: 0x7f0c0039
			public const int secondary_text_disabled_material_dark = 2131492921;
			
			// aapt resource value: 0x7f0c003a
			public const int secondary_text_disabled_material_light = 2131492922;
			
			// aapt resource value: 0x7f0c003b
			public const int switch_thumb_disabled_material_dark = 2131492923;
			
			// aapt resource value: 0x7f0c003c
			public const int switch_thumb_disabled_material_light = 2131492924;
			
			// aapt resource value: 0x7f0c0061
			public const int switch_thumb_material_dark = 2131492961;
			
			// aapt resource value: 0x7f0c0062
			public const int switch_thumb_material_light = 2131492962;
			
			// aapt resource value: 0x7f0c003d
			public const int switch_thumb_normal_material_dark = 2131492925;
			
			// aapt resource value: 0x7f0c003e
			public const int switch_thumb_normal_material_light = 2131492926;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070018
			public const int abc_action_bar_content_inset_material = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int abc_action_bar_content_inset_with_nav = 2131165209;
			
			// aapt resource value: 0x7f07000d
			public const int abc_action_bar_default_height_material = 2131165197;
			
			// aapt resource value: 0x7f07001a
			public const int abc_action_bar_default_padding_end_material = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int abc_action_bar_default_padding_start_material = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int abc_action_bar_elevation_material = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int abc_action_bar_icon_vertical_padding_material = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int abc_action_bar_overflow_padding_end_material = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int abc_action_bar_overflow_padding_start_material = 2131165220;
			
			// aapt resource value: 0x7f07000e
			public const int abc_action_bar_progress_bar_size = 2131165198;
			
			// aapt resource value: 0x7f070025
			public const int abc_action_bar_stacked_max_height = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int abc_action_bar_stacked_tab_max_width = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int abc_action_bar_subtitle_bottom_margin_material = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int abc_action_bar_subtitle_top_margin_material = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int abc_action_button_min_height_material = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int abc_action_button_min_width_material = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int abc_action_button_min_width_overflow_material = 2131165227;
			
			// aapt resource value: 0x7f07000c
			public const int abc_alert_dialog_button_bar_height = 2131165196;
			
			// aapt resource value: 0x7f07002c
			public const int abc_button_inset_horizontal_material = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int abc_button_inset_vertical_material = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int abc_button_padding_horizontal_material = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int abc_button_padding_vertical_material = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int abc_cascading_menus_min_smallest_width = 2131165232;
			
			// aapt resource value: 0x7f070011
			public const int abc_config_prefDialogWidth = 2131165201;
			
			// aapt resource value: 0x7f070031
			public const int abc_control_corner_material = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int abc_control_inset_material = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int abc_control_padding_material = 2131165235;
			
			// aapt resource value: 0x7f070012
			public const int abc_dialog_fixed_height_major = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int abc_dialog_fixed_height_minor = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int abc_dialog_fixed_width_major = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int abc_dialog_fixed_width_minor = 2131165205;
			
			// aapt resource value: 0x7f070034
			public const int abc_dialog_list_padding_bottom_no_buttons = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int abc_dialog_list_padding_top_no_title = 2131165237;
			
			// aapt resource value: 0x7f070016
			public const int abc_dialog_min_width_major = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int abc_dialog_min_width_minor = 2131165207;
			
			// aapt resource value: 0x7f070036
			public const int abc_dialog_padding_material = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int abc_dialog_padding_top_material = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int abc_dialog_title_divider_material = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int abc_disabled_alpha_material_dark = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int abc_disabled_alpha_material_light = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int abc_dropdownitem_icon_width = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int abc_dropdownitem_text_padding_left = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int abc_dropdownitem_text_padding_right = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int abc_edit_text_inset_bottom_material = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int abc_edit_text_inset_horizontal_material = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int abc_edit_text_inset_top_material = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int abc_floating_window_z = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int abc_list_item_padding_horizontal_material = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int abc_panel_menu_list_width = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int abc_progress_bar_height_material = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int abc_search_view_preferred_height = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int abc_search_view_preferred_width = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int abc_seekbar_track_background_height_material = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int abc_seekbar_track_progress_height_material = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int abc_select_dialog_padding_start_material = 2131165257;
			
			// aapt resource value: 0x7f07001d
			public const int abc_switch_padding = 2131165213;
			
			// aapt resource value: 0x7f07004a
			public const int abc_text_size_body_1_material = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int abc_text_size_body_2_material = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int abc_text_size_button_material = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int abc_text_size_caption_material = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int abc_text_size_display_1_material = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int abc_text_size_display_2_material = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int abc_text_size_display_3_material = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int abc_text_size_display_4_material = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int abc_text_size_headline_material = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int abc_text_size_large_material = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int abc_text_size_medium_material = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int abc_text_size_menu_header_material = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int abc_text_size_menu_material = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int abc_text_size_small_material = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int abc_text_size_subhead_material = 2131165272;
			
			// aapt resource value: 0x7f07000f
			public const int abc_text_size_subtitle_material_toolbar = 2131165199;
			
			// aapt resource value: 0x7f070059
			public const int abc_text_size_title_material = 2131165273;
			
			// aapt resource value: 0x7f070010
			public const int abc_text_size_title_material_toolbar = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int cardview_compat_inset_shadow = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int cardview_default_elevation = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int cardview_default_radius = 2131165195;
			
			// aapt resource value: 0x7f070076
			public const int design_appbar_elevation = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int design_bottom_navigation_active_item_max_width = 2131165303;
			
			// aapt resource value: 0x7f070078
			public const int design_bottom_navigation_active_text_size = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int design_bottom_navigation_elevation = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int design_bottom_navigation_height = 2131165306;
			
			// aapt resource value: 0x7f07007b
			public const int design_bottom_navigation_item_max_width = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int design_bottom_navigation_item_min_width = 2131165308;
			
			// aapt resource value: 0x7f07007d
			public const int design_bottom_navigation_